name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push Debian image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: jamiephonic/rtmps-hls-server:latest
        
    - name: Push Alpine image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.alpine
        push: true
        tags: jamiephonic/rtmps-hls-server:latest-alpine
        
